// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const section: string;
export const wrapper: string;
export const blogList: string;
export const listItem: string;
export const imgWrapper: string;
export const timeWrapper: string;
