// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const blogPost: string;
export const prevLink: string;
export const nextLink: string;
export const link: string;
