// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const heroWrapper: string;
export const img: string;
export const textWrapper: string;
