// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const section: string;
export const wrapper: string;
export const sectionTitle: string;
export const tabList: string;
export const tab: string;
export const selected: string;
export const body: string;
export const itemList: string;
export const item: string;
export const imgWrapper: string;
export const itemName: string;
export const itemPrice: string;
export const itemBody: string;
